# Generated by Django 6.0.3 on 2026-04-13 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0004_appointment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('year_of_exp', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('CBC', 'Complete Blood Count'), ('LFT', 'Liver Function Test'), ('URINE TOTAL TEST', 'Urine Total Test'), ('URINE MICROSCOPIC', 'Urine Microscopic Examination'), ('SERUM ROUTINE', 'Serum Routine Test'), ('THYROID', 'Thyroid Function Test')], max_length=100)),
                ('lab_result', models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='ongoing', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_range', models.CharField(choices=[('Nill', 'Nill'), ('positive', 'positive'), ('negative', 'negative'), ('normal', 'normal'), ('abnormal', 'abnormal')], default='Nill', max_length=100)),
                ('result_desc', models.TextField(max_length=100)),
                ('test_cost', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reffered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
