# Generated by Django 6.0.3 on 2026-04-21 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0004_appointment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('date_of_admit', models.DateField()),
                ('date_of_discharge', models.DateField(auto_now_add=True)),
                ('room_type', models.CharField(choices=[('COMMON WARD', 'Common ward'), ('SEMI PRIVATE', 'Pemi private'), ('PRIVATE AC', 'Private AC'), ('PRIVATE NON AC', 'Private non AC'), ('DELLUX', 'Delux')], max_length=100)),
                ('food_required', models.BooleanField(default=False)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.treatment_details')),
            ],
        ),
    ]
