# Generated by Django 6.0.3 on 2026-04-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLDOCTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialisation', models.CharField(choices=[('GENERAL MEDICINE', 'general medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIC', 'orthopedic'), ('DENTIST', 'dentist'), ('NEUROLOGIST', 'neurologist'), ('OTHERS', 'others')])),
                ('yoe', models.IntegerField()),
                ('license_no', models.IntegerField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='TREATMENT_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GENERAL MEDICINE', 'general medicine'), ('CARDIOLOGIST', 'cardiologist'), ('ORTHOPEDIC', 'orthopedic'), ('DENTIST', 'dentist'), ('NEUROLOGIST', 'neurologist'), ('OTHERS', 'others')])),
                ('description', models.TextField()),
                ('dos', models.TextField(help_text='What to do')),
                ('donts', models.TextField(help_text='What to avoid')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
