# Generated by Django 6.0.3 on 2026-04-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('morning', '09:00 AM - 12:00 PM'), ('afternoon', '01:00 PM - 04:00 PM'), ('evening', '05:00 PM - 08:00 PM')], max_length=20),
        ),
    ]
